### ISSUE TITLE
Islands and pets ideas

### ISSUE THREAD

**Issue by gmgsplayer** [justusgamelab2016/LastWood#10]
My idea to the game. could add some really small islands, to gather sources, and make the submerse island system, so old islands disapear and new ones appear on the map. The raft could move in the sea to find the islands. Another idea is to have a pet (could combine with islands e.g: monkey pet in island) that can make you happy, like a boost, when you're happy you make things quicker than normal. Thats my idea, please, at least answer me ;-;

**Comment by justusgamelab2016** [comment]
Sorry for absence.Forgot to review the GitHub page totally.
Moving rafts is a cool idea. We will add mechanisms to enable survivors to move their raft.
As long as they can sail, of course they will encounter different kinds of islands.

Pets are necessary, too.

Thanks for your feedback. :D
