### ISSUE TITLE
Campfire not working

### ISSUE THREAD

**Issue by justusgamelab2016** [justusgamelab2016/LastWood#4]
my people don't like to do things sometimes, they will run back and forth in one area when i try and get them to cook on the campfire. They never actually put anything on the fire. the fish is just put in storage.

**Comment by munenari** [comment]
1. do fishing
2. cancel fishing (for attacking to a shark or so)
3. a fishing task will be crash?

**Comment by justusgamelab2016** [comment]
Productions making system had been remade in ver.0.3.0.
